version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "mocha"
  ]

[[analyzers]]
name = "test-coverage"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"